services:
  ace-pace:
    build: .
    image: ace-pace
    container_name: ace-pace
    volumes:
      - /path/to/OnePaceLibrary:/media:ro
    networks:
      - "proxy"
    # environment:
    #   - ACEPACE_URL=https://nyaa.si/?f=0&c=0_0&q=one+pace+720p&o=asc
    #   - ACEPACE_DB=true
    #   - ACEPACE_DOWNLOAD=transmission
networks:
  proxy:
    driver: bridge
