services:
  ace-pace:
    build: .
    image: ace-pace
    container_name: ace-pace
    volumes:
      - /path/to/OnePaceLibrary:/media:rw
    networks:
      - "proxy"
    environment:
      - TORRENT_HOST=127.0.0.1
      - TORRENT_PORT=9091
      - TORRENT_CLIENT=transmission
      #- NYAA_URL=https://nyaa.si/?f=0&c=0_0&q=one+pace+720p&o=asc
      #- TORRENT_USER=admin
      #- TORRENT_PASSWORD=password
      - DB=true
      - EPISODES_UPDATE=true
networks:
  proxy:
    driver: bridge
